### ISSUE TITLE
Use lighter default font colour

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#20]
Please use `#3c4043` instead of black for the default text colour

**Comment by personalizedrefrigerator** [comment]
Fixed in 490d4745485f032e71045cbac24e7068d023209a

![screenshot: Lighter default font](https://github.com/joplin/website-plugin-discovery/assets/46334387/07cdd2f5-5179-4939-a335-1bebd5adac1a)

I've kept the dark-mode color as-is for now:
![screenshot: Light text on a dark background](https://github.com/joplin/website-plugin-discovery/assets/46334387/bcec55b2-44b4-4586-ac2d-1dcd57c3918b)
