### ISSUE TITLE
Add a fourth plugin in "most popular" to make it more balanced

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#27]
<img width="1086" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/667fe6ee-5164-4e02-bd8b-f5f2f6380fba">

**Comment by personalizedrefrigerator** [comment]
Addressed in https://github.com/joplin/website-plugin-discovery/commit/cd2c1243feadd931ea63db802dc043e044664b59.

Note that only three plugins are still shown on some screen sizes, because $\texttt{3 plugins} = \texttt{1 row}$ in these cases.
![screenshot: 3 plugins in first row](https://github.com/joplin/website-plugin-discovery/assets/46334387/213835ab-8ec9-44b4-9e1e-06af4c860296)
![screenshot: wider screen and 4 plugins in first row](https://github.com/joplin/website-plugin-discovery/assets/46334387/b4f3b2cc-5a99-4ece-a1f7-0ab73d98952f)
