### ISSUE TITLE
Category links should get focus when using tabs

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#33]
- Put the cursor on the Search box
- Press tab - the cursor goes to Home
- Press tab again - the cursor goes to the plugin list

Instead it should go to the sidebar, and allows the user to go from one category to another using tab.

**Comment by personalizedrefrigerator** [comment]
This is now **partially** fixed.

The issue was caused by hiding the "Home" tab in the sidebar. Bootstrap gives non-focused tabs a `tabindex` of `-1`. Because the "Home" tab was hidden with `display: none`, no tabs in the sidebar were focusable when the home tab was selected.

For now, I'm showing the home tab in the sidebar when it has keyboard focus (and hiding it otherwise).

**Comment by khadar1020** [comment]
please can i solve this issue @laurent22  @personalizedrefrigerator
