### ISSUE TITLE
Improve styling of footer

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#40]
- Add some padding above the Copyright/T&C/Privacy link (Same padding as the "Home" link)
- Make it fit within the same width as the navbar container
- Change the T&C and Privacy Policy links to the same colour as the "Forum" link (dark gray)

<img width="880" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/3b418f74-51b1-446e-8a19-d82779ccaab5">

**Comment by personalizedrefrigerator** [comment]
## Updated footer
### Dark mode
![dark mode: Terms and conditions, privacy policy text is now grey and has more space both above and below. In addition, space has been added to the left and right of the links](https://github.com/joplin/website-plugin-discovery/assets/46334387/75d1f1a2-2ac3-49e7-ba32-5206c98d4f7e)

### Light mode
![light mode screenshot: Similar to above, but now grey on a light background rather than grey on a dark background](https://github.com/joplin/website-plugin-discovery/assets/46334387/c84f84d0-368a-49e7-a7ce-92e6051dbb81)

### On a plugin page
![screenshot -- similar to above. The links now line up with the page content](https://github.com/joplin/website-plugin-discovery/assets/46334387/a657a704-a1ef-41ba-bb78-2a68b3b09fd0)

**Comment by Ali7040** [comment]
@laurent22  I would like to take on this task. Please assign it to me.

**Comment by JackGruber** [comment]
We don't assign issues

**Comment by laurent22** [comment]
@personalizedrefrigerator, what would be the status of this issue, is there still something to do?

**Comment by personalizedrefrigerator** [comment]
> @personalizedrefrigerator, what would be the status of this issue, is there still something to do?

I don't think there's anything left to do ([see above comment](https://github.com/joplin/website-plugin-discovery/issues/40#issuecomment-1890232011)). I'm closing this as completed.
