### ISSUE TITLE
Add support for promo_tile manifest property

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#43]
I've documented the property here and will create a blog post about it soon:

https://joplinapp.org/help/api/references/plugin_manifest#promo-tile

This is basically the same as the "promo tile" in the Chrome Store:

<img width="892" alt="image" src="https://github.com/joplin/website-plugin-discovery/assets/1285584/7278884e-5878-4c54-b34f-ef81c1437dc0">

If the plugin provides one, we use it. Otherwise we use the icon. And if nothing is provided we display the default tile.

We only display it in the main page. In plugin page, we don't use the promo tile at all, and just use the icon like now.

**Comment by personalizedrefrigerator** [comment]
Addressed in commit https://github.com/joplin/website-plugin-discovery/commit/791293f5e136b5c85e5db0bb13d1e866f8a7b0ee:

![screenshot: All plugins, sorted by most recently updated. A few have promo tiles instead of icons, which cover the upper half of the plugin cards.](https://github.com/joplin/website-plugin-discovery/assets/46334387/2bd2942a-b912-4d2e-99ba-166d58887c81)

**Alt text**:
For now, I've given the promo tile icons empty alt text. To me these tiles mostly seem [to be decorative. According to the WC3 WAI's ALT-text tutorial, such images should not have alt text](https://www.w3.org/WAI/tutorials/images/decorative/). This also seems to be what Google's extension store does: 
![screenshot of developer tools inspecting a promo tile in the chrome web store. The promo tile's HTML includes alt=""](https://github.com/joplin/website-plugin-discovery/assets/46334387/1fb2dc7e-b827-4f0a-8863-d8f337d0169d)

**Comment by personalizedrefrigerator** [comment]
I'm closing this issue — promo tile support has been implemented.
