### ISSUE TITLE
Use a more discreet image for the "promo tile"

### ISSUE THREAD

**Issue by laurent22** [joplin/website-plugin-discovery#9]
The current image is a bit distracting, especially since for now it's repeated for each plugin. Instead how about a puzzle icon centered in the image? Something like this? (but please find another puzzle piece icon as this one requires attribution)

![image](https://github.com/joplin/website-plugin-discovery/assets/1285584/692fcca1-8a50-44e6-8a76-12f946cc9f68)

(I also think that the gear icon looks like work in progress, while the puzzle piece seems to be more recognised as a plugin icon (at least according to Google))

**Comment by personalizedrefrigerator** [comment]
Changed in 0e1ea9f6b37e213f6e9daf0cb37516dd45378f93

Before:
![screenshot: gear icon promo tiles](https://github.com/joplin/website-plugin-discovery/assets/46334387/5e55f7e0-d6f6-4835-aac6-b2ab084694ef)

After:
![screenshot: Plugin icon promo tiles](https://github.com/joplin/website-plugin-discovery/assets/46334387/d8b32488-2a2d-440f-9f6b-71d7585831fd)


Note that this also changes the default icon shown in the plugin details page:
![screenshot: Plugin icon used as plugin page icon](https://github.com/joplin/website-plugin-discovery/assets/46334387/8bf9a2bf-2404-4f57-acb1-7bd49e146d7a)

This is because both the tiles and plugin details pages use the icon specified by the plugin's manifest (or the default icon). See [the reveal.js plugin](https://joplin.github.io/website-plugin-discovery/plugin/io.github.personalizedrefrigerator.revealjs-integration/) for an example with an icon.

**Comment by personalizedrefrigerator** [comment]
This has been addressed (see above comments).
